### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HyrPiikk** [ValresMC/MineSystem#1]
[Server thread/CRITICAL]: Error: "Class "Valres\Mine\Listener\blockEvents" not found" (EXCEPTION) in "plugins/MineSystem-main/src/Valres/Mine/Main" at line 18
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(119): Valres\Mine\Main->onEnable()
  #1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1398): pocketmine\plugin\PluginManager->enablePlugin(object Valres\Mine\Main#45451)
  #3 pmsrc/src/Server(1034): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#45229)
  #4 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[23] /home/serveurbe/kitmap/, string[31] /home/serveurbe/kitmap/plugins/)
  #5 pmsrc/src/PocketMine(364): pocketmine\server()
  #6 pmsrc(11): require(string[67] phar:///home/serveurbe/kitmap/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by ValresMC** [comment]
Fix ! ^^

**Comment by ValresMC** [comment]
Fix ! ^^
